NB_NRN                  = 16
NB_FRAME_PER_BUFFER     = 190

DATAWIDTH_BIT_FRAME     = 32
DATAWIDTH_BYTE_FRAME    = int(DATAWIDTH_BIT_FRAME/8)
SIZE_BYTE_FRAME         = (1+NB_NRN)*DATAWIDTH_BYTE_FRAME # +1 for time stamp