NB_NRN                  = 1024
NB_FRAME_PER_BUFFER     = 100

DATAWIDTH_BIT_FRAME     = 32
DATAWIDTH_BYTE_FRAME    = int(DATAWIDTH_BIT_FRAME/8)
NB_SPK_DATA_PER_FRAME   = int(NB_NRN/DATAWIDTH_BIT_FRAME)
SIZE_BYTE_FRAME         = (NB_SPK_DATA_PER_FRAME+1)*DATAWIDTH_BYTE_FRAME # +1 for time stamp